version: "3.8"

services:
  ku_nginx:
    image: nginx:1.26.3
    container_name: ${PROJECT_IMAGE_NAME}_nginx
    restart: always
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${HOST_APP_PORT}:80"
    networks:
      - app_network

networks:
  app_network:
    name: ${COMPOSE_PROJECT_NAME}_app_network
    driver: bridge
    external: false
